### ISSUE TITLE
The contact form on your website is broken

### ISSUE THREAD

**Issue by fulldecent** [OpiumProtocol/erc721o#2]
The contact form at https://www.opium.network is broken.

Under "Subscribe to get early access" if you fill in the form and click CONTACT then the form erases.

Also, there is no other contact information available for the project.

Also GitHub is spelled wrong on the homepage.

**Comment by Alirun** [comment]
Hi @fulldecent ! Thank you for this issue. It actually works and supposed to work like this. 

We will change it to something more obvious.

We have got your details!
